package in.co.eko.fundu.database.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import in.co.eko.fundu.database.greendao.FunduTransaction;

import in.co.eko.fundu.database.greendao.FunduTransactionDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig funduTransactionDaoConfig;

    private final FunduTransactionDao funduTransactionDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        funduTransactionDaoConfig = daoConfigMap.get(FunduTransactionDao.class).clone();
        funduTransactionDaoConfig.initIdentityScope(type);

        funduTransactionDao = new FunduTransactionDao(funduTransactionDaoConfig, this);

        registerDao(FunduTransaction.class, funduTransactionDao);
    }
    
    public void clear() {
        funduTransactionDaoConfig.clearIdentityScope();
    }

    public FunduTransactionDao getFunduTransactionDao() {
        return funduTransactionDao;
    }

}
