package in.co.eko.fundu.database.greendao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "FUNDU_TRANSACTION".
 */
@Entity
public class FunduTransaction {

    @Id(autoincrement = true)
    private Long id;

    @Unique
    private String tid;
    private String seeker;
    private String provider;
    private String custid;
    private String phoneNumber;
    private String name;
    private String image;
    private String fee;
    private String rating;
    private String code;
    private String providerCharge;
    private Double latitude;
    private Double longitude;
    private String amount;
    private Integer state;
    private String status;
    private String pairRequestId;
    private Double requestLatitude;
    private Double requestLongitude;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public FunduTransaction() {
    }

    public FunduTransaction(Long id) {
        this.id = id;
    }

    @Generated
    public FunduTransaction(Long id, String tid, String seeker, String provider, String custid, String phoneNumber, String name, String image, String fee, String rating, String code, String providerCharge, Double latitude, Double longitude, String amount, Integer state, String status, String pairRequestId, Double requestLatitude, Double requestLongitude) {
        this.id = id;
        this.tid = tid;
        this.seeker = seeker;
        this.provider = provider;
        this.custid = custid;
        this.phoneNumber = phoneNumber;
        this.name = name;
        this.image = image;
        this.fee = fee;
        this.rating = rating;
        this.code = code;
        this.providerCharge = providerCharge;
        this.latitude = latitude;
        this.longitude = longitude;
        this.amount = amount;
        this.state = state;
        this.status = status;
        this.pairRequestId = pairRequestId;
        this.requestLatitude = requestLatitude;
        this.requestLongitude = requestLongitude;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTid() {
        return tid;
    }

    public void setTid(String tid) {
        this.tid = tid;
    }

    public String getSeeker() {
        return seeker;
    }

    public void setSeeker(String seeker) {
        this.seeker = seeker;
    }

    public String getProvider() {
        return provider;
    }

    public void setProvider(String provider) {
        this.provider = provider;
    }

    public String getCustid() {
        return custid;
    }

    public void setCustid(String custid) {
        this.custid = custid;
    }

    public String getPhoneNumber() {
        return phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public String getFee() {
        return fee;
    }

    public void setFee(String fee) {
        this.fee = fee;
    }

    public String getRating() {
        return rating;
    }

    public void setRating(String rating) {
        this.rating = rating;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getProviderCharge() {
        return providerCharge;
    }

    public void setProviderCharge(String providerCharge) {
        this.providerCharge = providerCharge;
    }

    public Double getLatitude() {
        return latitude;
    }

    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    public Double getLongitude() {
        return longitude;
    }

    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    public String getAmount() {
        return amount;
    }

    public void setAmount(String amount) {
        this.amount = amount;
    }

    public Integer getState() {
        return state;
    }

    public void setState(Integer state) {
        this.state = state;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getPairRequestId() {
        return pairRequestId;
    }

    public void setPairRequestId(String pairRequestId) {
        this.pairRequestId = pairRequestId;
    }

    public Double getRequestLatitude() {
        return requestLatitude;
    }

    public void setRequestLatitude(Double requestLatitude) {
        this.requestLatitude = requestLatitude;
    }

    public Double getRequestLongitude() {
        return requestLongitude;
    }

    public void setRequestLongitude(Double requestLongitude) {
        this.requestLongitude = requestLongitude;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
